version: "3.9"

services:
    app:
        container_name: project_todo_web
        image:  project_todo_web
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
